import Foundation

/**
 * AUTO-GENERATED FILE - Do not edit manually
 * Generated by scripts/generate-config.js from .env file
 * Single source of truth: .env file
 *
 * Identity is verified by UHP-v2 DID, not by TLS SPKI pinning.
 */

struct BootstrapGateway {
    let host: String
    let ip: String
    let did: String
}

struct GeneratedConfig {
    // Node/Server Configuration
    static let nodeUrl = "http://zhtp-gateway.thesovereignnetwork.org:9334"
    static let nodeHost = "zhtp-gateway.thesovereignnetwork.org"
    static let nodePort: UInt16 = 9334

    // Bootstrap gateways — first entry is primary, second is fallback.
    // The app dials these, then verifies the UHP-v2 handshake's peer_did
    // matches the configured did field. Mismatch is treated as MITM.
    static let bootstrapGateways: [BootstrapGateway] = [
        BootstrapGateway(host: "zhtp-gateway.thesovereignnetwork.org", ip: "91.98.113.188", did: "did:zhtp:placeholder"),
    ]
}
