package com.sovereignnetworkmobile.config

/**
 * AUTO-GENERATED FILE - Do not edit manually
 * Generated by scripts/generate-config.js from .env file
 * Single source of truth: .env file
 *
 * Identity is verified by UHP-v2 DID, not by TLS SPKI pinning.
 */

data class BootstrapGateway(
    val host: String,
    val ip: String,
    val did: String,
)

object GeneratedConfig {
    // Node/Server Configuration
    const val NODE_URL = "http://zhtp-gateway.thesovereignnetwork.org:9334"
    const val NODE_HOST = "zhtp-gateway.thesovereignnetwork.org"
    const val NODE_PORT = 9334

    // Bootstrap gateways — first entry is primary, second is fallback.
    // The app dials these, then verifies the UHP-v2 handshake's peer_did
    // matches the configured did field. Mismatch is treated as MITM.
    val BOOTSTRAP_GATEWAYS: List<BootstrapGateway> = listOf(
        BootstrapGateway(host = "zhtp-gateway.thesovereignnetwork.org", ip = "91.98.113.188", did = "did:zhtp:placeholder"),
    )
}
